### ISSUE TITLE
Cannot deploy a static HTML site

### ISSUE THREAD

**Issue by jackyzha0** [fission-codes/publish-action#20]
# Summary
I added this entry to my `deploy.yaml` file (link to [repo](https://github.com/jackyzha0/jackyzha0.github.io/blob/hugo/.github/workflows/deploy.yaml))

```yaml
  - name: Deploy on fission.codes
    uses: fission-suite/publish-action@v1
    with:
      machine_key: ${{ secrets.FISSION_MACHINE_KEY }}
      build_dir: ./public
```

However, the build fails with a missing library: `libtinfo.so.6: cannot open shared object file: No such file or directory`

## Problem
Stack trace

```
(node:3146) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Using fission CLI version: 2.18.0
/bin/chmod +x /home/runner/work/_temp/70b8761b-6550-423[9](https://github.com/jackyzha0/jackyzha0.github.io/runs/7796460116?check_suite_focus=true#step:8:10)-881a-5d4196f74c6c
/opt/hostedtoolcache/fission-cli/2.18.0/x64/fission setup --with-key /home/runner/work/_temp/machine_id.ed25519
/opt/hostedtoolcache/fission-cli/2.18.0/x64/fission: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
Error: The process '/opt/hostedtoolcache/fission-cli/2.18.0/x64/fission' failed with exit code [12](https://github.com/jackyzha0/jackyzha0.github.io/runs/7796460116?check_suite_focus=true#step:8:13)7
```

### Impact

Cannot use `publish-action`
